name: Test
on:
  pull_request:
    branches: [ main, develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer

jobs:
  test:
    runs-on: macos-15-large
    steps:
    - uses: actions/checkout@v4
  
    - name: Set up the development team
      env:
        DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
      run: |
        configuration="CODE_SIGN_STYLE = Automatic\nDEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM}\n"
        echo -e "$configuration" > ./Configurations/Signing.xcconfig

    - name: Run tests
      run: |
        chmod +x ./Scripts/test.sh
        ./Scripts/test.sh

    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results.xcresult
        path: ./Artifacts/test-results.xcresult
